resolver: lts-10.7

packages:
- location: .
- location: ../cabal-helper
  extra-dep: true

extra-deps: 
- extra-1.5.3
- monad-journal-0.7.2
- optparse-applicative-0.13.2.0
- unix-compat-0.4.3.1
- either-4.4.1.1
- cabal-plan-0.3.0.0
- ansi-terminal-0.8.0.4

                
flags: {}

extra-package-dbs: []


